# Generated by Django 3.2.5 on 2021-07-12 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serviço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviço_atual', models.CharField(max_length=60)),
                ('observacao2', models.CharField(blank=True, max_length=60, verbose_name='Observação:')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_atual', models.CharField(blank=True, max_length=60, verbose_name='Status:')),
                ('observacao3', models.CharField(blank=True, max_length=60, verbose_name='Observação:')),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tela_atual', models.CharField(max_length=60)),
                ('observacao1', models.CharField(blank=True, max_length=60, verbose_name='Observação:')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, verbose_name='Nome:')),
                ('proximo_pagamento', models.DateTimeField(max_length=90, null=True)),
                ('ultimo_pagamento', models.DateTimeField(max_length=90, null=True)),
                ('plano', models.ForeignKey(max_length=60, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.serviço')),
                ('status_agora', models.ForeignKey(max_length=60, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.status')),
                ('tela_agora', models.ForeignKey(max_length=60, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.tela')),
            ],
        ),
    ]
